### ISSUE TITLE
Are there any plans of supporting Ruby 2.2.4 and 2.3.0?

### ISSUE THREAD

**Issue by ciconia** [phusion/traveling-ruby#62]
Thanks for your fantastic work!

**Comment by Rush** [comment]
Bumping the question. Thank you for this awesome project.

**Comment by FooBarWidget** [comment]
Yes there are, but it depends on my free time. Right now I am working at 100% capacity on commercial  projects.

**Comment by develar** [comment]
I tried to build on OS X, but even 2.2.2 cannot be compiled (I updated openssl to 1.0.2h because f is not available anymore):

```
/private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/private/tmp/ruby-2.2.5/ruby-2.2.5/.ext/x86_64-darwin15/openssl.bundle, 9): Library not loaded: @executable_path/../lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /private/tmp/ruby-2.2.5/ruby-2.2.5/.ext/x86_64-darwin15/openssl.bundle
  Reason: image not found - /private/tmp/ruby-2.2.5/ruby-2.2.5/.ext/x86_64-darwin15/openssl.bundle
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/.ext/common/openssl.rb:17:in `<top (required)>'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/security.rb:11:in `<top (required)>'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/package.rb:43:in `<top (required)>'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/dependency_installer.rb:3:in `<top (required)>'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /private/tmp/ruby-2.2.5/ruby-2.2.5/lib/rubygems.rb:556:in `install'
	from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:721:in `each'
	from ./tool/rbinstall.rb:721:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
```

I want to use traveling-ruby to pack fpm because require Ruby in project electorn-buidler is a nightmare.

Will be cool if someone point me how to fix this error.

**Comment by develar** [comment]
Linux build successful after some changes: https://github.com/develar/traveling-ruby/commit/777c2f8d977c090c7548fac0c6251849155d0c8c#diff-6972a469eaabdbbeae552dbd8502881fR13

I will publish new version (ruby 2.3.1) and updated native exts in my fork when it will be tested (~one week).

**Comment by develar** [comment]
2.3.1 available for Linux in my fork: https://github.com/develar/traveling-ruby/releases

Changes:
* distribute in xz format
* build real Docker image — you can build ruby for Linux on OS X (not yet tried, but no problem anymore)
* update cmake, openssl, libssh and other libs to latest versions
* base OS is still centos 6.7 (but it set explicitly in the Dockerfile instead of just 6).

Version scheme is changed — ${ruby_version}-${optional-patch-release-number}.

@FooBarWidget You can get my changes https://github.com/develar/traveling-ruby/commits/master or, if you will have time, I can prepare PR here.

**Comment by hackhowtofaq** [comment]
Any news guys?

**Comment by Rush** [comment]
@develar I tried to build binaries from your repo but I'm getting:

```
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/sbin/my_init\\\": stat /sbin/my_init: no such file or directory\"\n".
```

Seems that `phusion/traveling-ruby-builder` does not even contain the directory `/system`:
```
rush@bob:~/traveling-ruby/linux$ rake
./setup-docker-image
+ cd /home/rush/traveling-ruby/linux
+ exec docker build --force-rm -t phusion/traveling-ruby-builder-base .
Sending build context to Docker daemon 80.38 kB
Step 1 : FROM centos:6.7
 ---> ab44245321a8
Step 2 : COPY image /image
 ---> Using cache
 ---> 801bdbd6a050
Step 3 : RUN /image/install.sh
 ---> Using cache
 ---> 2ae434d85de0
Step 4 : COPY internal /system
 ---> Using cache
 ---> 760e6a72888e
Successfully built 760e6a72888e
mkdir -p runtime/2.3.1-x86
./setup-runtime -a x86 -r 2.3.1 runtime/2.3.1-x86
Preparing
------------------------------------------
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/system/my_init\\\": stat /system/my_init: no such file or directory\"\n".
rake aborted!
Command failed with status (127): [./setup-runtime -a x86 -r 2.3.1 runtime/2....]
/home/rush/traveling-ruby/linux/Rakefile:68:in `block (3 levels) in <top (required)>'
Tasks: TOP => default => package => package:2.3.1:x86 => traveling-ruby-2.3.1-linux-x86.tar.xz => output/2.3.1-x86/bin => runtime/2.3.1-x86/ok
(See full trace by running task with --trace)
```

**Comment by Rush** [comment]
@develar Do you have a backup of `phusion/traveling-ruby-builder`? Maybe somebody from `phusion` upload a broken version to the DockerHub or something along the lines.

**Comment by zw963** [comment]
@develar , build failed.  
```sh
╰─ $ 127  ./setup-runtime -a x86_64 -r 2.3.1 runtime/2.3.1-x86_64/
Preparing
------------------------------------------
container_linux.go:247: starting container process caused "exec: \"/system/my_init\": stat /system/my_init: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/system/my_init\": stat /system/my_init: no such file or directory".
ERRO[0000] error getting events from daemon: net/http: request canceled 
```

**Comment by johnjelinek** [comment]
@develar: I tested today with your `v2.3.1` tag and `master` branch and both fail here:
```
Complete!
+ create_user app App 1000
+ local name=app
+ local full_name=App
+ local id=1000
+ create_group app 1000
+ local name=app
+ local id=1000
+ grep -q '^app:' /etc/group
+ groupadd --gid 1000 app
+ grep -q '^app:' /etc/passwd
+ adduser --uid 1000 --gid 1000 --comment App app
+ usermod -L app
+ usermod -a -G mock app
+ mkdir -p /etc/container_environment /etc/workaround-docker-2267
+ ln -s /etc/workaround-docker-2267 /cte
+ rm -rf /image /tmp/anaconda-post.log /tmp/ks-script-mbvg2Y /tmp/yum.log
rm: cannot remove `/image': Directory not empty
Removing intermediate container 32f50584410b
The command '/bin/sh -c /image/install.sh' returned a non-zero code: 1
rake aborted!
Command failed with status (1): [./setup-docker-image...]
/home/user/traveling-ruby/linux/Rakefile:66:in `block (3 levels) in <top (required)>'
Tasks: TOP => package:2.3.1:x86_64 => traveling-ruby-20160506-2.3.1-linux-x86_64.tar.xz => output/2.3.1-x86_64/bin => runtime/2.3.1-x86_64/ok
(See full trace by running task with --trace)
```

**Comment by johnjelinek** [comment]
@develar: I removed the command in `install.sh` to `rm -rf /image` and next error:
```
Transaction Summary
================================================================================
Install     207 Package(s)
Upgrade       0 Package(s)

Total download size: 163 M
Downloading Packages:
--------------------------------------------------------------------------------
Total                                           5.5 MB/s | 163 MB     00:29
warning: rpmts_HdrFromFdno: Header V4 DSA signature: NOKEY, key ID 217521f6


GPG key retrieval failed: [Errno 5] OSError: [Errno 2] No such file or directory: '/usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-5'
Finish: shell
rake aborted!
Command failed with status (1): [./setup-runtime -a x86_64 -r 2.3.1 runtime...]
/home/user/traveling-ruby/linux/Rakefile:67:in `block (3 levels) in <top (required)>'
Tasks: TOP => build:2.3.1:x86_64 => output/2.3.1-x86_64/bin => runtime/2.3.1-x86_64/ok
(See full trace by running task with --trace)
```

**Comment by FloorD** [comment]
referencing this in #88 and adding a milestone to add Ruby versions support.
